# Generated by Django 5.1.2 on 2024-11-09 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.CharField(max_length=10)),
                ('Question', models.TextField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
