# Generated by Django 5.1.2 on 2024-11-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='data',
            new_name='date',
        ),
    ]
