# Generated by Django 5.1.2 on 2024-11-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0002_rename_data_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Question',
            new_name='question',
        ),
    ]
