# Generated by Django 5.1.2 on 2024-11-11 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('specilization', models.CharField(max_length=100)),
                ('qualification', models.FileField(upload_to='doctor/')),
                ('experinces', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(upload_to='doctor_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=55)),
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('', 'select gender'), ('male', 'male'), ('female', 'female')], max_length=6)),
                ('problem', models.TextField()),
                ('doctor_email', models.EmailField(max_length=50)),
                ('profile_picture', models.FileField(upload_to='patient_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='voice_constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('prescription', models.FileField(upload_to='patient/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='patient/')),
                ('audio_file', models.FileField(upload_to='patient/')),
                ('submisson_date', models.DateField(default=django.utils.timezone.now)),
                ('response_audio_file', models.FileField(upload_to='patient/')),
                ('response_date', models.DateField(default='')),
                ('response_status', models.CharField(max_length=10)),
            ],
        ),
    ]
