# Generated by Django 5.1.2 on 2024-11-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0005_doctor_patient_voice_constellation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='patient',
        ),
    ]
