# Generated by Django 5.1.2 on 2024-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0006_delete_doctor_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('specilization', models.CharField(max_length=100)),
                ('qualification', models.FileField(upload_to='doctor/')),
                ('experinces', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(upload_to='doctor_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=55)),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('', 'select gender'), ('male', 'male'), ('female', 'female')], max_length=6)),
                ('problem', models.TextField()),
                ('doctor_email', models.EmailField(max_length=50)),
                ('profile_picture', models.FileField(upload_to='patient_profile/')),
            ],
        ),
    ]
