# Generated by Django 5.1.1 on 2024-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0007_doctor_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_constellation',
            name='response_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
