# Generated by Django 5.1.1 on 2024-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0008_alter_voice_constellation_response_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice_constellation',
            name='id',
        ),
        migrations.AlterField(
            model_name='voice_constellation',
            name='patient_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
