# Generated by Django 5.1.1 on 2024-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0009_remove_voice_constellation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
